sudo: required

language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t lekvar21/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run lekvar21/udemy-docker-react yarn run test -- --coverage
