sudo: required

language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t lekvar21/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lekvar21/udemy-docker-react yarn run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-853210130410"
  bucket_path: "udemy-docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
